In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
#define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
# one hot representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[3384, 5712, 9333, 1022],
 [3384, 5712, 9333, 1261],
 [3384, 3809, 9333, 2776],
 [1778, 3984, 6030, 102, 7917],
 [1778, 3984, 6030, 102, 8477],
 [1020, 3384, 6054, 9333, 8581],
 [6658, 5689, 7917, 102]]

In [10]:
## word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
sent_len=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_len)
print(embedded_docs)

[[   0    0    0    0 3384 5712 9333 1022]
 [   0    0    0    0 3384 5712 9333 1261]
 [   0    0    0    0 3384 3809 9333 2776]
 [   0    0    0 1778 3984 6030  102 7917]
 [   0    0    0 1778 3984 6030  102 8477]
 [   0    0    0 1020 3384 6054 9333 8581]
 [   0    0    0    0 6658 5689 7917  102]]


In [13]:
## feature representation
dim=10


In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_len))
model.compile('adam','mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 307ms/step


array([[[-2.15142015e-02,  3.44223268e-02,  4.16105986e-03,
         -1.93699729e-02,  1.40583031e-02, -4.24392112e-02,
          1.48320198e-03, -2.97331102e-02, -3.22638825e-03,
          2.01128460e-02],
        [-2.15142015e-02,  3.44223268e-02,  4.16105986e-03,
         -1.93699729e-02,  1.40583031e-02, -4.24392112e-02,
          1.48320198e-03, -2.97331102e-02, -3.22638825e-03,
          2.01128460e-02],
        [-2.15142015e-02,  3.44223268e-02,  4.16105986e-03,
         -1.93699729e-02,  1.40583031e-02, -4.24392112e-02,
          1.48320198e-03, -2.97331102e-02, -3.22638825e-03,
          2.01128460e-02],
        [-2.15142015e-02,  3.44223268e-02,  4.16105986e-03,
         -1.93699729e-02,  1.40583031e-02, -4.24392112e-02,
          1.48320198e-03, -2.97331102e-02, -3.22638825e-03,
          2.01128460e-02],
        [-4.77699749e-02,  3.05773877e-02,  3.26233245e-02,
         -7.75747374e-03, -1.41833313e-02,  1.38298757e-02,
         -1.34184733e-02,  2.46659406e-02,  5.421686